apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flask-jwt-auth-web
resources:
- kubernetes/postgres-data-persistentvolumeclaim.yaml
- kubernetes/env-prod-db-configmap.yaml
- kubernetes/env-prod-configmap.yaml
- kubernetes/db-deployment.yaml
- kubernetes/web-deployment.yaml
- kubernetes/db-service.yaml
- kubernetes/web-service.yaml
