apiVersion: v1
data:
  DATABASE: postgres
  DATABASE_URL: postgresql://hello_flask:hello_flask@db:5432/hello_flask_prod
  FLASK_APP: project/__init__.py
  FLASK_ENV: production
  SQL_HOST: db
  SQL_PORT: "5432"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web-env-prod
  name: env-prod
